// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTRrgM-IcQe6WB7qTzZIjEsYIkNkKyZo4',
    appId: '1:705083505760:web:3bd1e8f802149d91131705',
    messagingSenderId: '705083505760',
    projectId: 'grocery-app-28f9a',
    authDomain: 'grocery-app-28f9a.firebaseapp.com',
    storageBucket: 'grocery-app-28f9a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS6dhqnQ1uv-BFrtMry-kV_CDgMhy-eb8',
    appId: '1:705083505760:android:98e9222f3fc55ec2131705',
    messagingSenderId: '705083505760',
    projectId: 'grocery-app-28f9a',
    storageBucket: 'grocery-app-28f9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCTqkQY3Y2DKgQiKgRUAbAQTY_Y7sEbWc',
    appId: '1:705083505760:ios:70e9d46134335dd7131705',
    messagingSenderId: '705083505760',
    projectId: 'grocery-app-28f9a',
    storageBucket: 'grocery-app-28f9a.firebasestorage.app',
    iosBundleId: 'com.example.groceryStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCTqkQY3Y2DKgQiKgRUAbAQTY_Y7sEbWc',
    appId: '1:705083505760:ios:70e9d46134335dd7131705',
    messagingSenderId: '705083505760',
    projectId: 'grocery-app-28f9a',
    storageBucket: 'grocery-app-28f9a.firebasestorage.app',
    iosBundleId: 'com.example.groceryStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTRrgM-IcQe6WB7qTzZIjEsYIkNkKyZo4',
    appId: '1:705083505760:web:92424f883aebe5eb131705',
    messagingSenderId: '705083505760',
    projectId: 'grocery-app-28f9a',
    authDomain: 'grocery-app-28f9a.firebaseapp.com',
    storageBucket: 'grocery-app-28f9a.firebasestorage.app',
  );
}
